---
#  _
# | |                 _      ____                _    _     
# | |    _   _   ___ | | __ |  _ \   ___   __ _ | |_ | |__  
# | |   | | | | / __|| |/ / | | | | / _ \ / _` || __|| '_ \ 
# | |___| |_| || (__ |   <  | |_| ||  __/| (_| || |_ | | | |
# |_____|\__,_| \___||_|\_\ |____/  \___| \__,_| \__||_| |_|
# 
# LuckDeath by Anders
# QQ: 480177664
# Mail: fox404@foxmail.com
# GitHub: https://github.com/Anders233

# 请勿修改此参数!!!
配置文件版本: 2

# 是否开启死亡不掉落物品功能?( true 或 false )
开启死亡不掉落: true

# 是否开启死亡随机掉落物品功能?( true 或 false )
开启死亡随机掉落物品: true

# 设置死亡随机掉落世界
# 示例：
# 死亡随机掉落世界: []                           - 在所有世界启用此功能
# 死亡随机掉落世界: ["world"]                    - 在 world 世界启用此功能
# 死亡随机掉落世界: ["world", "末地", "地狱"]    - 在 world,末地,地狱 世界启用此功能
死亡随机掉落物品世界: []

# 如果开启物品死亡随机掉落物品功能
# 请设置掉落武器几率(百分比)
死亡随机掉落物品几率: 50

# 死亡随机扣除钱( 需要 EconomyAPI )
# 是否开启死亡随机扣钱?( true 或 false )
死亡随机扣钱: true
# 死亡随机扣除钱基础数量
死亡随机扣钱数量: 1000
# 死亡随机扣除钱浮动数量
死亡随机扣钱浮动: 500
# 例如数量是1000，浮动是50
# 那么就会随机扣除500到1500的钱
...
